export const JOB_TYPE_DELETE_REQUEST = "JOB_TYPE_DELETE_REQUEST";
export const JOB_TYPE_DELETE_SUCCESS = "JOB_TYPE_DELETE_SUCCESS";
export const JOB_TYPE_DELETE_FAILURE = "JOB_TYPE_DELETE_FAILURE";
export const JOB_TYPE_DELETE_RESET = "JOB_TYPE_DELETE_RESET";
