export const LOAD_JOB_TYPE_REQUEST = "LOAD_JOB_TYPE_REQUEST";
export const LOAD_JOB_TYPE_SUCCESS = "LOAD_JOB_TYPE_SUCCESS";
export const LOAD_JOB_TYPE_FAILURE = "LOAD_JOB_TYPE_FAILURE";
export const LOAD_JOB_TYPE_RESET = "LOAD_JOB_TYPE_RESET";
