export const SINGLE_USER_LOAD_REQUEST = "SINGLE_USER_LOAD_REQUEST";
export const SINGLE_USER_LOAD_SUCCESS = "SINGLE_USER_LOAD_SUCCESS";
export const SINGLE_USER_LOAD_FAILURE = "SINGLE_USER_LOAD_FAILURE";
export const SINGLE_USER_LOAD_RESET = "SINGLE_USER_LOAD_RESET";
