export const CREATE_CAT_REQUEST = "CREATE_CAT_REQUEST";
export const CREATE_CAT_SUCCESS = "CREATE_CAT_SUCCESS";
export const CREATE_CAT_FAILURE = "CREATE_CAT_FAILURE";
export const CREATE_CAT_RESET = "CREATE_CAT_RESET";
