export const JOB_DELETE_REQUEST = "JOB_DELETE_REQUEST";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAILURE = "JOB_DELETE_FAILURE";
export const JOB_DELETE_RESET = "JOB_DELETE_RESET";
