export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAILURE = "USER_REG_FAILURE";
export const USER_REG_RESET = "USER_REG_RESET";
